FROM python:alpine3.12

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update && \
    apk --no-cache add gcc musl-dev python3-dev libffi-dev openssl-dev sshpass openssh-client

RUN pip --no-cache-dir install ansible -i https://mirrors.aliyun.com/pypi/simple


CMD ["/usr/local/bin/ansible","--version"]